services:
  - type: web
    name: nlp-gymtracker
    env: docker
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - requirements.txt
        - Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
